
version: "3.9"

services:
  django:
    build: ./backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    # env_file:
      # - ./.env.dev
    volumes:
      - ./backend/:/srv/app
    network_mode: host

  react:
    build: ./frontend
    container_name: react
    command: npm start
    ports:
      - 3000:3000
    # env_file:
    #   - ./.env.dev
    network_mode: host
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/srv/app
      - /srv/app/node_modules
    depends_on:
      - django
